version: "3.8" # 버전을 명시적으로 지정

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENV=development
    volumes:
      - ./:/app:ro # readonly로 변경
    restart: unless-stopped
